<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <UserSecretsId>dotnet-MazyPlatform.Service.Notification-29319a4c-8309-417d-bc8c-3f809e8bc669</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" />
        <PackageReference Include="MazyPlatform.Contracts.User" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
        <PackageReference Include="MimeKit" />
        <PackageReference Include="prometheus-net.AspNetCore" />
        <PackageReference Include="RabbitMQ.Client" />
        <PackageReference Include="Scrutor" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Enrichers.Environment" />
        <PackageReference Include="Serilog.Enrichers.Thread" />
        <PackageReference Include="Serilog.Extensions.Hosting" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Settings.Configuration" />
        <PackageReference Include="Serilog.Sinks.Async" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.Grafana.Loki" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
</Project>
