FROM node:22-alpine AS build
WORKDIR /app

ARG VITE_API_URL=
ARG VITE_YANDEX_CLIENT_ID=
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_YANDEX_CLIENT_ID=$VITE_YANDEX_CLIENT_ID

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.29-alpine AS final
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
