<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="MazyPlatform.Contracts.Scenario" />
      <PackageReference Include="MazyPlatform.Contracts.User" />
      <PackageReference Include="MazyPlatform.Scenario" />
      <PackageReference Include="MazyPlatform.Scenario.Abstractions" />
      <PackageReference Include="MazyPlatform.Scenario.Telegram" />
      <PackageReference Include="MazyPlatform.Scenario.Vk" />
      <PackageReference Include="MazyPlatform.SharedKernel.Application" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MazyPlatform.Service.Scenario.Repository.Domain\MazyPlatform.Service.Scenario.Repository.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="**\*Command.cs">
            <DependentUpon>$([System.String]::Copy('%(Filename)').Replace('Command', 'Handler')).cs</DependentUpon>
        </Compile>
        <Compile Update="**\*Query.cs">
            <DependentUpon>$([System.String]::Copy('%(Filename)').Replace('Query', 'Handler')).cs</DependentUpon>
        </Compile>
        <Compile Update="**\*Result.cs">
            <DependentUpon>$([System.String]::Copy('%(Filename)').Replace('Result', 'Handler')).cs</DependentUpon>
        </Compile>
        <Compile Update="**\*Validator.cs">
            <DependentUpon>$([System.String]::Copy('%(Filename)').Replace('Validator', 'Handler')).cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
