<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>
        <PackageId>MazyPlatform.Contracts.Scenario.Grpc</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Api.CommonProtos" />
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>build</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Grpc.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Repository/**/*.proto" GrpcServices="Both" ProtoRoot="Repository" />
    </ItemGroup>

</Project>
