<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" />
        <PackageReference Include="MazyPlatform.Contracts.Bot.Grpc" />
        <PackageReference Include="MazyPlatform.Contracts.User" />
        <PackageReference Include="MazyPlatform.SharedKernel.Infrastructure" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
        <PackageReference Include="MongoDB.Driver" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="RabbitMQ.Client" />
        <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MazyPlatform.Service.Scenario.Repository.Application\MazyPlatform.Service.Scenario.Repository.Application.csproj" />
        <ProjectReference Include="..\MazyPlatform.Service.Scenario.Repository.Domain\MazyPlatform.Service.Scenario.Repository.Domain.csproj" />
    </ItemGroup>

</Project>
