<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MazyPlatform.Service.User.Authentication.Domain\MazyPlatform.Service.User.Authentication.Domain.csproj" />
    </ItemGroup>

</Project>
