// <auto-generated />
using System;
using MazyPlatform.Service.User.Authentication.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MazyPlatform.Service.User.Authentication.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.MfaSessions.MfaSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.PrimitiveCollection<string>("CompletedFactors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("completed_factors");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsCompletedByBackupCode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed_by_backup_code");

                    b.Property<int>("RequiredFactorCount")
                        .HasColumnType("integer")
                        .HasColumnName("required_factor_count");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("mfa_sessions", (string)null);
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.OneTimePasswords.OneTimePassword", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("one_time_passwords", (string)null);
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.LinkedProviders.UserLinkedProviders", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("user_linked_providers", (string)null);
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.Mfa.MfaMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MfaSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("mfa_settings_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MfaSettingsId");

                    b.ToTable("mfa_methods", (string)null);
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.Mfa.MfaSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackupCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("backup_codes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("mfa_settings", (string)null);
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("PasswordSetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_set_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserSessions.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid>("RefreshTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int?>("RevokedReason")
                        .HasColumnType("integer")
                        .HasColumnName("revoked_reason");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.MfaSessions.MfaSession", b =>
                {
                    b.HasOne("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.OneTimePasswords.OneTimePassword", b =>
                {
                    b.HasOne("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.LinkedProviders.UserLinkedProviders", b =>
                {
                    b.HasOne("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.UserAccount", null)
                        .WithOne("UserLinkedProviders")
                        .HasForeignKey("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.LinkedProviders.UserLinkedProviders", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.LinkedProviders.ExternalProvider", "LinkedProviders", b1 =>
                        {
                            b1.Property<Guid>("user_linked_providers_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_linked_providers_id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("user_linked_providers_id", "Type");

                            b1.ToTable("user_external_providers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_linked_providers_id");
                        });

                    b.Navigation("LinkedProviders");
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.Mfa.MfaMethod", b =>
                {
                    b.HasOne("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.Mfa.MfaSettings", null)
                        .WithMany("MfaMethods")
                        .HasForeignKey("MfaSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.Mfa.MfaSettings", b =>
                {
                    b.HasOne("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.UserAccount", null)
                        .WithOne("MfaSettings")
                        .HasForeignKey("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.Mfa.MfaSettings", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserSessions.UserSession", b =>
                {
                    b.HasOne("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.Mfa.MfaSettings", b =>
                {
                    b.Navigation("MfaMethods");
                });

            modelBuilder.Entity("MazyPlatform.Service.User.Authentication.Domain.UserAccounts.UserAccount", b =>
                {
                    b.Navigation("MfaSettings")
                        .IsRequired();

                    b.Navigation("UserLinkedProviders")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
